blank_issues_enabled: false
contact_links:
  - name: LUCA Dev Assistant Documentation
    url: https://github.com/ZeroSumQuant/luca-dev-assistant/docs
    about: Check out the documentation for more information
