name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Global job timeout
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt
          python -m pip install -e .
          
      - name: Display environment info
        run: |
          python -c "import sys; print(f'Python version: {sys.version}')"
          python -c "import psutil; print(f'Available memory: {psutil.virtual_memory().available / (1024**3):.2f} GB')"
          python -m pip list
          # Verify pytest installation
          python -c "import pytest; print(f'Pytest version: {pytest.__version__}')"
      
      - name: Run mocked tests (AutoGen fake responses)
        run: |
          python -m pytest -m autogen_mock -q
        env:
          LUCA_TESTING: 1
          CI: true
          PYTHONPATH: .
          
      - name: Run real-execution tests
        run: |
          python -m pytest -m "not autogen_mock" -q --timeout=60 --timeout_method=thread
        env:
          LUCA_TESTING: 1
          CI: true
          PYTHONPATH: .

      - name: Docker build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false   # change to true + set secrets if you want auto-push
          tags: luca-dev:ci

      - name: Docker-capped tests
        run: make test-docker
