name: Quality gate

on: [push, pull_request, workflow_dispatch]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt
          python -m pip install -e .
          
      - name: Lint & format
        run: |
          black --check .
          isort --check-only .
          flake8 --config=.config/.flake8
          
      - name: Unit tests
        run: |
          pytest -q
        env:
          LUCA_TESTING: 1