name: Update Changelog

on:
  pull_request:
    types: [closed]
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    # run if: merged PR → main  OR  direct push → main
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # Need full git history for changelog generation
          fetch-depth: 0
          # Use a token with write permissions
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install conventional-changelog-cli
        run: npm install -g conventional-changelog-cli

      - name: Regenerate changelog
        run: conventional-changelog -p angular -i docs/handoff/changelog.md -s

      - name: Commit changelog if changed
        id: commit
        run: |
          if git diff --quiet docs/handoff/changelog.md ; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add docs/handoff/changelog.md
            git commit -m "chore: update changelog [skip ci]"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Push commit with robust sync handling
        if: steps.commit.outputs.has_changes == 'true'
        run: |
          # First fetch latest changes from origin
          git fetch origin main
          
          # Try to rebase our changes on top of latest main
          if ! git rebase origin/main; then
            # If rebase fails, abort it and try a different approach
            git rebase --abort
            
            # Save our current changelog changes
            cp docs/handoff/changelog.md /tmp/changelog.md.new
            
            # Get the latest main branch state
            git checkout main
            git pull origin main
            
            # Apply our saved changes
            cp /tmp/changelog.md.new docs/handoff/changelog.md
            
            # Re-stage and commit
            git add docs/handoff/changelog.md
            git commit -m "chore: update changelog [skip ci]"
          fi
          
          # Finally push changes to main branch with extra safeguards
          git push origin HEAD:main || {
            echo "Push failed, trying one more time with forced update of local state"
            git fetch origin main --force
            git reset --hard origin/main
            
            # Apply our changelog changes again
            cp /tmp/changelog.md.new docs/handoff/changelog.md
            git add docs/handoff/changelog.md
            git commit -m "chore: update changelog [skip ci]"
            git push origin HEAD:main
          }
